server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-occupancy-planning
  datasource:
    url: jdbc:h2:mem:occupancy;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    serialization:
      indent_output: true
    default-property-inclusion: non_null

logging:
  level:
    root: INFO
    com.xai.occupancy: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
